### PR TITLE
Fail with "401 Unauthorized" when token is not provided to User.logout()

### LINKED ISSUE #1669: User.logout() return 500 error if auth token not found
I think this is related to https://github.com/strongloop/loopback/issues/1489 but it seems to me that if an auth token is not found, Strongloop should assume the request is unauthorized and return http code 401. Currently, it returns a 500 error which implies the server is broken.

**EDIT**: upon further inspection of the code, it looks like the error is happening explicitly when `User.logout()` is called and the access token does not exist in the database. I can see how a `500` error could make sense in this situation but it might make more sense for the method to simply return success.

### PR DESCRIPTION
**Pull request by ritch**
Connect to https://github.com/strongloop/strong-arc/issues/1414

Fix #1669

### CODE REVIEW

File: common/models/user.js [hunk 1]
```diff
@@ -269,6 +269,14 @@ module.exports = function(User) {
...
 
   User.logout = function(tokenId, fn) {
+    if(!tokenId) {
+      process.nextTick(function() {
+        var err = new Error('access token is required to logout');
+        err.status = 400;
+        fn(err);
+      });
+      return;
+    }
```
Comment (raymondfeng) [inline common/models/user.js]: Should https://github.com/strongloop/loopback/blob/fix/logout-without-token/common/models/user.js#L286 throw an error with statusCode set to 404 or 400 too?

**Comment by raymondfeng** [comment]
Connect to #1489

**Comment by bajtos** [comment]
I find it surprising that the error was not caught by strong-remoting, since the argument is marked as required. The solution proposed here is fine though.

File: common/models/user.js [hunk 2]
```diff
@@ -269,6 +269,14 @@ module.exports = function(User) {
...
     this.relations.accessTokens.modelTo.findById(tokenId, function(err, accessToken) {
```
Comment (raymondfeng) [inline common/models/user.js]: Can this just be `this.accessTokens.destroyById(tokenId, function(err) {...}`? I also wondering if we need to provide feedback if the access_token is invalid.

**Comment by raymondfeng** [comment]
@ritch Assigning back to you to address the comments.

**Comment by kevintechie** [comment]
According to the HTTP 1.1 RFC, if the Authorization header is missing, the response must be 401 Unauthorized and respond with an appropriate WWW-Authenticate header. If the Authorization header is  rejected (i. e. the access token is not found in the database), the response must also be 401.

Loopback returns a 401 for other REST requests that require authorization if the Authorization header is missing. It should return 401 for user/logout as well. Loopback does not respond with a WWW-Authenticate header as required, however.

Loopback also returns a 401 for other REST requests if the Authorization header is invalid. It should also return 401 for user/logout if the Authorization header is invalid.

According to the RFC, the response can include diagnostic information as to why the Authorization was rejected: http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.2 Perhaps Loopback should as well -- similar to how Oauth 2.0 Bearer tokens are implemented.

**Comment by bajtos** [comment]
Hi @kevintechie, thank you for the description of what a correct behaviour should be per the HTTP spec. 

Would you mind taking this patch over, rebasing it on top of the current master and submitting a new PR where I can help you to get the code into the shape where it can be landed? Or you can start from a scratch and treat this patch as a source of inspiration only, if that's easier for you.

**Comment by seanmangar** [comment]
Is this still open? I implemented this by overriding the base ACLs for user and applying the ACL below. I think this could be directly done in the loopback common/models/user.json.

```
    {
      "principalType": "ROLE",
      "principalId": "$authenticated",
      "permission": "ALLOW",
      "property": "logout"
    },
```

**Comment by bajtos** [comment]
I think this problem is quite important and we should fix it. I am reassigning the pull request to myself.

**Comment by bajtos** [comment]
@raymondfeng I have addressed your comments, does the patch LGTY now?

> I also wondering if we need to provide feedback if the access_token is invalid.

We should be returning 401 based on @kevintechie's https://github.com/strongloop/loopback/pull/1496#issuecomment-157469342 and that's what I have implemented here.

@kevintechie @seanmangar Please feel free to review my proposed changes and give me feedback what to fix/improve before merging.

File: common/models/user.js [hunk 3]
```diff
@@ -752,10 +762,10 @@ module.exports = function(User) {
       {
         description: 'Logout a user with access token.',
         accepts: [
-          {arg: 'access_token', type: 'string', required: true, http: function(ctx) {
```
Comment (bajtos) [inline common/models/user.js]: With `required:true`, logout without any access tokens returns 400 because strong-remoting rejects the request as missing required arguments.

File: common/models/user.js [hunk 4]
```diff
@@ -752,10 +762,10 @@ module.exports = function(User) {
...
+          {arg: 'access_token', type: 'string', http: function(ctx) {
             var req = ctx && ctx.req;
             var accessToken = req && req.accessToken;
-            var tokenID = accessToken && accessToken.id;
+            var tokenID = accessToken ? accessToken.id : undefined;
```
Comment (bajtos) [inline common/models/user.js]: The original code returned `null` when there was no token provided. strong-remoting does not accept `null` as a `string` value, therefore logout with no access token failed with 400 "missing required argument".

File: common/models/user.js (hunk 3 above)
Comment (raymondfeng) [inline common/models/user.js]: Why is 400 worse than 401 if the token is not provided? IMO, it's better to report it as missing argument.

Comment (kevintechie) [inline common/models/user.js]: The RFC says that it should be 401. Client frameworks expect 401 and subsequent WWW-Authenticate header to respond correctly. Also, other loopback APIs respond correctly with 401 when the token is missing.

Comment (raymondfeng) [inline common/models/user.js]: Got it. +1 to be consistent.

**Comment by bajtos** [comment]
Landed 🎉
