### PR TITLE
Fix user-literal rewrite for anonymous requests

### LINKED ISSUE #3291: invalid token on currentUserLiteral throws 500
# Description/Steps to reproduce
When loading fixtures in our dev/staging environments, our token table gets reset and all clients that were previously logged in start receiving 500 responses at currentUserLiteral endpoints with the error: 
```
500 invalid input syntax for integer: "me"
length: 91
severity: ERROR
code: 22P02
file: numutils.c
line: 62
routine: pg_atoi
error: invalid input syntax for integer: "me"
    at Connection.parseE (/.../node_modules/pg/lib/connection.js:569:11)
    at Connection.parseMessage (/.../node_modules/pg/lib/connection.js:396:17)
    at Socket. (/.../node_modules/pg/lib/connection.js:132:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
```

In looking into this we found that the authToken was being invalidated and unset, and the default findById method was being called with our currentUserLiteral as the id which throws a SQL error. 

*update*
The cause seems to be the if on line L25 of [token.js](https://github.com/strongloop/loopback/blob/master/server/middleware/token.js#L25-L34). If the access token is not set, then this request is processed by `Model.findById`. 

# Expected result

Expected a 401 Unauthorized response

# Additional information

We've temporarily worked around this with the following:
```
const router = server.loopback.Router();
const currentUserLiteral = 'me';
router.all(
    `/api/{model}/${currentUserLiteral}`,
    catchInvalidAuthForCurrentUserLiteral
);
server.use(router);

function catchInvalidAuthForCurrentUserLiteral(req, res, next) {
  if (req.accessToken == null) res.sendStatus(401);
  else next();
}
```

Env info:
```
$ node -e 'console.log(process.platform, process.arch, process.versions.node)'
darwin x64 6.9.5

$ npm ls --prod --depth 0 | grep loopback
├── loopback@3.4.0
├── loopback-boot@2.23.0
├── loopback-component-explorer@4.1.1
├── loopback-component-passport@3.2.0
├── loopback-connector-postgresql@2.8.0
├── loopback-fixtures@0.0.10 invalid
```

### PR DESCRIPTION
**Pull request by aaronbuchanan**
### Description

Currently any `currentUserLiteral` routes when accessed with a bad token throw a 500 due to a SQL error that is raised because `Model.findById` is invoked with `id={currentUserLiteral}` (`id=me` in our case) when the url rewrite fails. 

This PR will render a 401 response on currentUserLiteral routes instead. 

#### Related issues

- #3291 invalid token on currentUserLiteral throws 500

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

File: server/middleware/token.js [hunk 1]
```diff
@@ -32,6 +32,9 @@ function rewriteUserLiteral(req, currentUserLiteral) {
       debug('req.url has been rewritten from %s to %s', urlBeforeRewrite,
         req.url);
     }
+  } else if (!req.accessToken && currentUserLiteral &&
```
Comment (bajtos) [inline server/middleware/token.js]: http://loopback.io/doc/en/contrib/style-guide.html#indentation-of-multi-line-expressions-in-if

I am proposing the following:

```js
function rewriteUserLiteral(req, currentUserLiteral) {
  if (!currentUserLiteral) return;
  
  if (req.accessToken && req.accessToken.userId) {
    // ...
  } else if (...) {
    // ...
  }
}
```

File: server/middleware/token.js [hunk 2]
```diff
@@ -32,6 +32,9 @@ function rewriteUserLiteral(req, currentUserLiteral) {
...
+      new RegExp(currentUserLiteral).test(req.url)) {
```
Comment (bajtos) [inline server/middleware/token.js]: This will match requests that do not contain current user literal. Assuming the literal is `me`, this will match requests like `/products/watermelon` too.

My proposal: use the same regexp as on L29.

```js
function rewriteUserLiteral(req, currentUserLiteral) {
  if (!currentUserLiteral) return;
  const literalRegExp = new RegExp('/' + currentUserLiteral + '(/|$|\\?)', 'g');
  // ...
}

File: server/middleware/token.js [hunk 3]
```diff
@@ -32,6 +32,9 @@ function rewriteUserLiteral(req, currentUserLiteral) {
...
+    req.res.status(401).end();
```
Comment (bajtos) [inline server/middleware/token.js]: This will by-pass the application error handler, which will result in an inconsistent error response.

You should create a new `Error` object and pass it to `next` function which was provided to `token` middleware handler.

File: test/access-token.test.js [hunk 4]
```diff
@@ -289,6 +289,33 @@ describe('loopback.token(options)', function() {
...
     });
 
+  it('should generate a 401 on a current user literal route without an authToken',
+    function(done) {
+      var app = createTestApp(null, done);
+      request(app)
+        .get('/users/me')
+        .set('authorization', null)
+        .expect(401)
+        .end(function(err, res) {
```
Comment (bajtos) [inline test/access-token.test.js]:
```js
.end(done);
```

File: test/access-token.test.js [hunk 5]
```diff
@@ -289,6 +289,33 @@ describe('loopback.token(options)', function() {
...
+
+  it('should generate a 401 on a current user literal route with invalid authToken',
+    function(done) {
+      var app = createTestApp(this.token, done);
+      var invalidTokenStub = {id: 'stub id'};
+      request(app)
+        .get('/users/me')
+        .set('Authorization', invalidTokenStub.id)
+        .expect(401)
+        .end(function(err, res) {
```
Comment (bajtos) [inline test/access-token.test.js]:
```js
.end(done)
```

File: test/access-token.test.js [hunk 6]
```diff
@@ -289,6 +289,33 @@ describe('loopback.token(options)', function() {
...
+        });
+    });
+
+  it('should generate a 401 on a current user literal route with invalid authToken',
+    function(done) {
+      var app = createTestApp(this.token, done);
+      var invalidTokenStub = {id: 'stub id'};
+      request(app)
+        .get('/users/me')
+        .set('Authorization', invalidTokenStub.id)
```
Comment (bajtos) [inline test/access-token.test.js]: No need to create `invalidTokenStub` object, just pass a string that makes it clear it's an invalid token id.

```js
.set('Authorization', 'invalid-token-id')
```

**Comment by bajtos** [comment]
@slnode test please

File: server/middleware/token.js (hunk 1 above)
Comment (aaronbuchanan) [inline server/middleware/token.js]: Love it, thought about a guard clause there, but didn't want to introduce seemingly unnecessary changes. Will update!

File: server/middleware/token.js (hunk 2 above)
Comment (aaronbuchanan) [inline server/middleware/token.js]: Good catch! [lol](https://gist.github.com/aaronbuchanan/cbaa38f45b6e4ae6ec00e9d5f707acdb)

File: server/middleware/token.js (hunk 3 above)
Comment (aaronbuchanan) [inline server/middleware/token.js]: ok, I wasn't sure if it was better to `throw` or `return`, prob picked the wrong one but this is updated 👍

**Comment by aaronbuchanan** [comment]
@bajtos I think I've addressed your points, let me know if you see anything else!

**Comment by aaronbuchanan** [comment]
rebased per [pr linter](https://ci.sl.strongloop.com/job/strongloop-pr-linter-jobs/job/loopback/1268/console)

File: server/middleware/token.js [hunk 7]
```diff
@@ -22,16 +23,25 @@ module.exports = token;
...
-      new RegExp('/' + currentUserLiteral + '(/|$|\\?)', 'g'),
+    req.url = req.url.replace(literalRegExp,
         '/' + req.accessToken.userId + '$1');
+
     if (req.url !== urlBeforeRewrite) {
       debug('req.url has been rewritten from %s to %s', urlBeforeRewrite,
         req.url);
     }
+  } else if (!req.accessToken && literalRegExp.test(req.url)) {
+    req.res.status(401).end();
```
Comment (bajtos) [inline server/middleware/token.js]: You shouldn't be touching the `res` object in this method. Let the error handler middleware decide how to handle the error.

Sorry if my original comment didn't make this clear.

File: server/middleware/token.js [hunk 8]
```diff
@@ -101,24 +111,26 @@ function token(options) {
...
 
+    var err = null;
     if (req.accessToken !== undefined) {
       if (!enableDoublecheck) {
         // req.accessToken is defined already (might also be "null" or "false") and enableDoublecheck
         // has not been set --> skip searching for credentials
-        rewriteUserLiteral(req, currentUserLiteral);
-        return next();
+        err = rewriteUserLiteral(req, currentUserLiteral);
+        return next(err);
```
Comment (bajtos) [inline server/middleware/token.js]: While this solution definitely works, it's quite an unusual pattern.

In Node.js world, the convention for functions is to accept a callback argument and then pass any errors to that callback.

```js
rewriteUserLiteral(req, currentUserLiteral, next);
```

File: server/middleware/token.js [hunk 9]
```diff
@@ -101,24 +111,26 @@ function token(options) {
...
       // continue normal operation (as if req.accessToken was undefined)
     }
+
     TokenModel.findForRequest(req, options, function(err, token) {
       req.accessToken = token || null;
-      rewriteUserLiteral(req, currentUserLiteral);
+      err = err || rewriteUserLiteral(req, currentUserLiteral);
       var ctx = req.loopbackContext;
       if (ctx && ctx.active) ctx.set('accessToken', token);
       next(err);
```
Comment (bajtos) [inline server/middleware/token.js]: I am proposing to clean up this block a bit while we are changing it.

```js
TokenModel.findForRequest(req, options, function(err, token) {
  if (err) {
    req.accessToken = null;
    return next(err);
  }

  var ctx = req.loopbackContext;
  if (ctx && ctx.active) ctx.set('accessToken', token);

  rewriteUserLiteral(req, currentUserLiteral, next);
}
```

**Comment by bajtos** [comment]
@slnode ok to test

File: server/middleware/token.js (hunk 7 above)
Comment (aaronbuchanan) [inline server/middleware/token.js]: Oh geez, that was a mistake. Should have been removed when adding the error.

File: server/middleware/token.js (hunk 8 above)
Comment (aaronbuchanan) [inline server/middleware/token.js]: I considered that initially but didn't like transferring responsibility to call `next()` to rewriteUserLiteral because it wasn't always the last call. Since we've refactored the findForRequest I think it makes more sense to pass `next in now.

**Comment by aaronbuchanan** [comment]
Hey @bajtos! I've made the changes, some other tests started failing and it's unclear why to me. In debugging, I see that some of the failing test scenarios are trying to access userLiteral routes with null `accessToken` values (where `(!req.accessToken && literalRegExp.test(req.url))` is true)

In looking further it appears `req.loopbackContext` is null and so `if (ctx && ctx.active) ctx.set('accessToken', token);` doesn't get called. 

Any idea?

File: server/middleware/token.js [hunk 10]
```diff
@@ -101,27 +112,31 @@ function token(options) {
     assert(typeof TokenModel === 'function',
       'loopback.token() middleware requires a AccessToken model');
 
+    var err = null;
```
Comment (bajtos) [inline server/middleware/token.js]: I think this can be removed.

**Comment by bajtos** [comment]
@aaronbuchanan sorry for responding so late!

> Any idea?

Not really :(

> some of the failing test scenarios are trying to access userLiteral routes with null `accessToken` values (where `(!req.accessToken && literalRegExp.test(req.url))` is true).

That's surprising. Which tests are attempting to do that?

> In looking further it appears `req.loopbackContext` is null and so `ctx.set('accessToken', token);` doesn't get called. 

I think `req.loopbackContext` shouldn't be related to user-literal rewriting. AFAIK, the only place where we are using `req.loopbackContext` is the token middleware. Those few lines of code are there to make it easier for `loopback-context` users to access the currently-logged-in user without having to install a new middleware.

**Comment by bajtos** [comment]
Hey, it turns out my code example in https://github.com/strongloop/loopback/pull/3292#discussion_r107709032 contained a severe bug - `req.accessToken` was not set when the token was authenticated. I fixed the problem in dfb19e7

**Comment by bajtos** [comment]
Landed, thank you for the contribution! 🎉
