### PR TITLE
fix: exit early when password is non-string

### LINKED ISSUE #1437: server break down if password is in numeric form on reset password
server get break down if i give password as numeric in reset password case because it is handled as number so number.indexOf() get break

### PR DESCRIPTION
**Pull request by BerkeleyTrue**
prevent errors when plain is non-string by using call on indexOf method
closes #1437

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
Any feedback on this?

File: common/models/user.js [hunk 1]
```diff
@@ -544,7 +544,11 @@ module.exports = function(User) {
     this.settings.ttl = this.settings.ttl || DEFAULT_TTL;
 
     UserModel.setter.password = function(plain) {
-      if (plain.indexOf('$2a$') === 0 && plain.length === 60) {
+      var indexOf = String.prototype.indexOf;
+      if (!plain) {
+        return;
+      }
+      if (indexOf.call(plain, '$2a$') === 0 && plain.length === 60) {
```
Comment (raymondfeng) [inline common/models/user.js]: Why do you have to the reflection api instead of `plain.indexOf`?

Comment (BerkeleyTrue) [inline common/models/user.js]: #1437 states that if plain is type number indexOf breaks as it a method on string instances. Using indexOf.call keeps this from breaking on numbers as it will cast it to string first.

**Comment by BerkeleyTrue** [comment]
Any way we can move this along? I really don't like the idea of having to support our own fork of loopback for lack of this PR.

**Comment by BerkeleyTrue** [comment]
@raymondfeng I hate to ping you directly but it is important that this fix gets in. Our development servers using loopback have shown lots of promise, but the fact that there has been no traction on this issue scares me.

If there is anything I can do to help move this along please let me know.

File: common/models/user.js (hunk 1 above)
Comment (BerkeleyTrue) [inline common/models/user.js]: I can remove the indexOf.call if it will help move things along.

The main thing I am worried about is users who have no passwords throwing and crashing.

The indexOf call was added as a bonus as address #1437

**Comment by BerkeleyTrue** [comment]
ping @raymondfeng

File: common/models/user.js (hunk 1 above)
Comment (raymondfeng) [inline common/models/user.js]: I would rather test if typeof plain === 'string'.

**Comment by raymondfeng** [comment]
Sorry for the delay. It skipped out of my eyes. I added a comment.

File: common/models/user.js (hunk 1 above)
Comment (BerkeleyTrue) [inline common/models/user.js]: like this?
```js
if (typeof plain !== 'string') {
  return;
}
```

Comment (BerkeleyTrue) [inline common/models/user.js]: @raymondfeng I don't think this really covers our use case. Most of our users coming in through github/twitter auth, they don't set passwords. We need to make sure users who do not have passwords do not crash the site just by logging in. 

I can get ride of the indexOf reflection and just set it to this:
```js
    UserModel.setter.password = function(plain) {
      if (!plain) {
        return;
      }
      if (plain.indexOf('$2a$') === 0 && plain.length === 60) {
        // The password is already hashed. It can be the case
        // when the instance is loaded from DB
        this.$password = plain;
      } else {
        this.$password = this.constructor.hashPassword(plain);
      }
    };
```

This prevents crashes when plain is undefined, which is the use case I am trying to solve, but won't do anything for the case when plain is a number, which I don't really need right now. 

@raymondfeng How does that sound?

Comment (raymondfeng) [inline common/models/user.js]: The following test returns for null, undefined, and non-strings.
```
if (typeof plain !== 'string') {
  return;
}
```

Comment (BerkeleyTrue) [inline common/models/user.js]: Got it. Will do.

**Comment by BerkeleyTrue** [comment]
@raymondfeng done
